.TH "Poznaj_Mape_Swiata" 3 "Fri Dec 23 2022" "Version v1.0" "Poznaj Europe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poznaj_Mape_Swiata
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "Interaction logic for App\&.xaml  "
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "Klasa główna programu  "
.ti -1c
.RI "class \fBPoziom2\fP"
.br
.RI "Interaction logic for Poziom2\&.xaml  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Poznaj Europe from the source code\&.
