.TH "Poznaj_Mape_Swiata.App" 3 "Fri Dec 23 2022" "Version v1.0" "Poznaj Europe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Poznaj_Mape_Swiata.App \- Interaction logic for App\&.xaml   

.SH SYNOPSIS
.br
.PP
.PP
Inherits Application\&.
.SH "Detailed Description"
.PP 
Interaction logic for App\&.xaml  

.SH "Author"
.PP 
Generated automatically by Doxygen for Poznaj Europe from the source code\&.
