Poznaj_Mape_Swiata::Poziom2
int Poznaj_Mape_Swiata.Poziom2.time
czas gry w sekundach
Referenced by Poznaj_Mape_Swiata.Poziom2.Dobrze, Poznaj_Mape_Swiata.Poziom2.Timer_Tick.
DispatcherTimer Poznaj_Mape_Swiata.Poziom2.Timer
Zmienna systemowa odpowiedzialna za kontrole uplywu czasu
Referenced by Poznaj_Mape_Swiata.Poziom2.CzyWybranoStolice, Poznaj_Mape_Swiata.Poziom2.Dobrze, Poznaj_Mape_Swiata.Poziom2.Poziom2, Poznaj_Mape_Swiata.Poziom2.Timer_Tick, Poznaj_Mape_Swiata.Poziom2.Zle.
int Poznaj_Mape_Swiata.Poziom2.ile_jeszcze
Zmienna odpowiedzialna za odliczanie stolic, ktore pozostaly do odgadniecia
Referenced by Poznaj_Mape_Swiata.Poziom2.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
int Poznaj_Mape_Swiata.Poziom2.zycie
zmienna liczaca zycia gracza
Referenced by Poznaj_Mape_Swiata.Poziom2.Poziom2, Poznaj_Mape_Swiata.Poziom2.Zle.
Image [] Poznaj_Mape_Swiata.Poziom2.zycia
Obiekt przechowujacy obrazki zycia na ekranie gracza
Referenced by Poznaj_Mape_Swiata.Poziom2.Poziom2, Poznaj_Mape_Swiata.Poziom2.Zle.
bool Poznaj_Mape_Swiata.Poziom2.hasBeenClicked
Zmienna kontrolujaca czyszczenie pola do wpisywania nazw krajow
Referenced by Poznaj_Mape_Swiata.Poziom2.Btnsprawdz_Click, Poznaj_Mape_Swiata.Poziom2.txt_kraj_GotFocus.
bool Poznaj_Mape_Swiata.Poziom2.SecondStage
Gra dysponuje dwoma etapami - odgadnij kraj ze stolicy oraz pokaz na mapie (tu rozpoczecie drugiego etapu rozgrywki po poprawnym wpisaniu nazwy kraju)
Referenced by Poznaj_Mape_Swiata.Poziom2.CzyWybranoStolice, Poznaj_Mape_Swiata.Poziom2.LV_stolic_MouseLeave.
Dictionary<String, String> Poznaj_Mape_Swiata.Poziom2.dopasowanie
Obiekt przechowujacy pary zmiennych stolica-kraj
Referenced by Poznaj_Mape_Swiata.Poziom2.Btnsprawdz_Click, Poznaj_Mape_Swiata.Poziom2.Dopasuj.
Random Poznaj_Mape_Swiata.Poziom2.rnd
Obiekt odpowiedzialny za losowanie
Referenced by Poznaj_Mape_Swiata.Poziom2.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
RadioButton [] Poznaj_Mape_Swiata.Poziom2.radios
Tablica przechowujaca kontrolki typu radio z nazwami stolic
Referenced by Poznaj_Mape_Swiata.Poziom2.Btnsprawdz_Click, Poznaj_Mape_Swiata.Poziom2.CzyWybranoStolice, Poznaj_Mape_Swiata.Poziom2.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
String [] Poznaj_Mape_Swiata.Poziom2.nazwy_stolic
Tablica z nazwami stolic
Referenced by Poznaj_Mape_Swiata.Poziom2.Dopasuj, Poznaj_Mape_Swiata.Poziom2.PrzygotowaniePoziomu.
int Poznaj_Mape_Swiata.Poziom2.poziom
Zmienna przechowujaca dany poziom
Referenced by Poznaj_Mape_Swiata.Poziom2.CzyWybranoStolice, Poznaj_Mape_Swiata.Poziom2.Dobrze, Poznaj_Mape_Swiata.Poziom2.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.Poziom2.sprawdzMape, Poznaj_Mape_Swiata.Poziom2.UpdateLabels.
int Poznaj_Mape_Swiata.Poziom2.punkty
Zmienna przechowujaca liczbe punktow gracza
Referenced by Poznaj_Mape_Swiata.Poziom2.Btnsprawdz_Click, Poznaj_Mape_Swiata.Poziom2.Poziom2, Poznaj_Mape_Swiata.Poziom2.sprawdzMape, Poznaj_Mape_Swiata.Poziom2.Timer_Tick, Poznaj_Mape_Swiata.Poziom2.UpdateLabels.
void Poznaj_Mape_Swiata.Poziom2.Dopasuj()
Metoda przechowująca pary: województwo-stolica
References Poznaj_Mape_Swiata.Poziom2.dopasowanie, Poznaj_Mape_Swiata.Poziom2.nazwy_stolic.
Referenced by Poznaj_Mape_Swiata.Poziom2.Poziom2.
void Poznaj_Mape_Swiata.Poziom2.UpdateLabels()
Metoda aktualizująca kontrolki przechowujących punkty i poziom
References Poznaj_Mape_Swiata.Poziom2.poziom, Poznaj_Mape_Swiata.Poziom2.punkty.
Referenced by Poznaj_Mape_Swiata.Poziom2.Btnsprawdz_Click, Poznaj_Mape_Swiata.Poziom2.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.PrzygotowaniePoziomu()
Metoda przygotowująca poziom do gry. Nastepuje w niej losowanie nazw stolic w czasie gry
References Poznaj_Mape_Swiata.Poziom2.ile_jeszcze, Poznaj_Mape_Swiata.Poziom2.nazwy_stolic, Poznaj_Mape_Swiata.Poziom2.poziom, Poznaj_Mape_Swiata.Poziom2.radios, Poznaj_Mape_Swiata.Poziom2.rnd, Poznaj_Mape_Swiata.Poziom2.UpdateLabels.
Referenced by Poznaj_Mape_Swiata.Poziom2.Poziom2, Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
Poznaj_Mape_Swiata.Poziom2.Poziom2(int zycie, int punkty)
Konstruktor programu inicjujacy gre
References Poznaj_Mape_Swiata.Poziom2.Dopasuj, Poznaj_Mape_Swiata.Poziom2.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.Poziom2.punkty, Poznaj_Mape_Swiata.Poziom2.Timer, Poznaj_Mape_Swiata.Poziom2.Timer_Tick, Poznaj_Mape_Swiata.Poziom2.zycia, Poznaj_Mape_Swiata.Poziom2.zycie.
void Poznaj_Mape_Swiata.Poziom2.Dobrze()
Metoda odpowiedzialna za reagowanie na poprawne odpowiedzi gracz
References Poznaj_Mape_Swiata.Poziom2.poziom, Poznaj_Mape_Swiata.Poziom2.time, Poznaj_Mape_Swiata.Poziom2.Timer.
Referenced by Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Zle()
Metoda odpowiedzialna za reagowanie na bledne odpowiedzi gracza oraz koniec gry.
References Poznaj_Mape_Swiata.Poziom2.Timer, Poznaj_Mape_Swiata.Poziom2.zycia, Poznaj_Mape_Swiata.Poziom2.zycie.
Referenced by Poznaj_Mape_Swiata.Poziom2.Btnsprawdz_Click, Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.WskazNaMapie()
Metoda odpowiedzialna za drugi etap rundy - wskazywanie na mapie
Referenced by Poznaj_Mape_Swiata.Poziom2.Btnsprawdz_Click.
int Poznaj_Mape_Swiata.Poziom2.CzyWybranoStolice()
Metoda sprawdzająca, która stolica została wybrana do odgadnięcia
Zwraca i-nr stolicy w przypadku poprawnego wyboru lub -1 w przypadku braku wyboru
References Poznaj_Mape_Swiata.Poziom2.poziom, Poznaj_Mape_Swiata.Poziom2.radios, Poznaj_Mape_Swiata.Poziom2.SecondStage, Poznaj_Mape_Swiata.Poziom2.Timer.
Referenced by Poznaj_Mape_Swiata.Poziom2.Btnsprawdz_Click, Poznaj_Mape_Swiata.Poziom2.LV_stolic_MouseLeave, Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Timer_Tick(object sender, EventArgs e)
Metoda odpowiedzialna za wyswietlanie oraz odliczanie czasu na gre w rundzie
sender Obiekt e Wydarzenie
References Poznaj_Mape_Swiata.Poziom2.punkty, Poznaj_Mape_Swiata.Poziom2.time, Poznaj_Mape_Swiata.Poziom2.Timer.
Referenced by Poznaj_Mape_Swiata.Poziom2.Poziom2.
void Poznaj_Mape_Swiata.Poziom2.Btnsprawdz_Click(object sender, RoutedEventArgs e)
Metoda odpowiedzialna za sprawdzenie czy wybrana stolica pasuje do wpisanego wojewodztwa
sender Objekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.CzyWybranoStolice, Poznaj_Mape_Swiata.Poziom2.dopasowanie, Poznaj_Mape_Swiata.Poziom2.hasBeenClicked, Poznaj_Mape_Swiata.Poziom2.punkty, Poznaj_Mape_Swiata.Poziom2.radios, Poznaj_Mape_Swiata.Poziom2.UpdateLabels, Poznaj_Mape_Swiata.Poziom2.WskazNaMapie, Poznaj_Mape_Swiata.Poziom2.Zle.
void Poznaj_Mape_Swiata.Poziom2.txt_kraj_GotFocus(object sender, RoutedEventArgs e)
Metoda odpowiedzialna za usuwanie domyslnego tekstu z pola do wpisywania nazwy województwa
sender Obiekt e Zdarzenie klikniecia w pole tekstowe
References Poznaj_Mape_Swiata.Poziom2.hasBeenClicked.
void Poznaj_Mape_Swiata.Poziom2.sprawdzMape(String nazwa, Button btn)
Metoda odpowiedzialna za sprawdzenie poprawnosci zaznaczenia wojewodztwa na mapie
nazwa Nazwa wojewodztwa btn Przycisk reprezentujacy obszar danego wojewodztwa
References Poznaj_Mape_Swiata.Poziom2.CzyWybranoStolice, Poznaj_Mape_Swiata.Poziom2.Dobrze, Poznaj_Mape_Swiata.Poziom2.ile_jeszcze, Poznaj_Mape_Swiata.Poziom2.poziom, Poznaj_Mape_Swiata.Poziom2.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.Poziom2.punkty, Poznaj_Mape_Swiata.Poziom2.radios, Poznaj_Mape_Swiata.Poziom2.rnd, Poznaj_Mape_Swiata.Poziom2.UpdateLabels, Poznaj_Mape_Swiata.Poziom2.Zle.
Referenced by Poznaj_Mape_Swiata.Poziom2.Button_Click_1, Poznaj_Mape_Swiata.Poziom2.Button_Click_10, Poznaj_Mape_Swiata.Poziom2.Button_Click_11, Poznaj_Mape_Swiata.Poziom2.Button_Click_12, Poznaj_Mape_Swiata.Poziom2.Button_Click_13, Poznaj_Mape_Swiata.Poziom2.Button_Click_14, Poznaj_Mape_Swiata.Poziom2.Button_Click_15, Poznaj_Mape_Swiata.Poziom2.Button_Click_16, Poznaj_Mape_Swiata.Poziom2.Button_Click_17, Poznaj_Mape_Swiata.Poziom2.Button_Click_18, Poznaj_Mape_Swiata.Poziom2.Button_Click_19, Poznaj_Mape_Swiata.Poziom2.Button_Click_2, Poznaj_Mape_Swiata.Poziom2.Button_Click_20, Poznaj_Mape_Swiata.Poziom2.Button_Click_21, Poznaj_Mape_Swiata.Poziom2.Button_Click_22, Poznaj_Mape_Swiata.Poziom2.Button_Click_23, Poznaj_Mape_Swiata.Poziom2.Button_Click_24, Poznaj_Mape_Swiata.Poziom2.Button_Click_25, Poznaj_Mape_Swiata.Poziom2.Button_Click_26, Poznaj_Mape_Swiata.Poziom2.Button_Click_27, Poznaj_Mape_Swiata.Poziom2.Button_Click_28, Poznaj_Mape_Swiata.Poziom2.Button_Click_29, Poznaj_Mape_Swiata.Poziom2.Button_Click_3, Poznaj_Mape_Swiata.Poziom2.Button_Click_30, Poznaj_Mape_Swiata.Poziom2.Button_Click_31, Poznaj_Mape_Swiata.Poziom2.Button_Click_32, Poznaj_Mape_Swiata.Poziom2.Button_Click_33, Poznaj_Mape_Swiata.Poziom2.Button_Click_34, Poznaj_Mape_Swiata.Poziom2.Button_Click_35, Poznaj_Mape_Swiata.Poziom2.Button_Click_36, Poznaj_Mape_Swiata.Poziom2.Button_Click_4, Poznaj_Mape_Swiata.Poziom2.Button_Click_5, Poznaj_Mape_Swiata.Poziom2.Button_Click_6, Poznaj_Mape_Swiata.Poziom2.Button_Click_7, Poznaj_Mape_Swiata.Poziom2.Button_Click_8, Poznaj_Mape_Swiata.Poziom2.Button_Click_9.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_1(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_2(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_3(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_4(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_5(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_6(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_7(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_8(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_9(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_10(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_11(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_12(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_13(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_14(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_15(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_16(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_17(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_18(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_19(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_20(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_21(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_22(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_23(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_24(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_25(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_26(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_27(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_28(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_29(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_30(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_31(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_32(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_33(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_34(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_35(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.Button_Click_36(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.Poziom2.sprawdzMape.
void Poznaj_Mape_Swiata.Poziom2.LV_stolic_MouseLeave(object sender, MouseEventArgs e)
Metoda odpowiedzialna za odczytanie z wylosowanej listy wybranego przez uzytkownika wojewodztwa
sender e
References Poznaj_Mape_Swiata.Poziom2.CzyWybranoStolice, Poznaj_Mape_Swiata.Poziom2.SecondStage.
void Poznaj_Mape_Swiata.Poziom2.Jeszcze_raz_Click(object sender, RoutedEventArgs e)
Metoda, ktora po przegranej nastepuje mozliwosc ponownej gry
sender Obiekt e Zdarzenie klikniecia