Poznaj_Mape_Swiata::MainWindow
int Poznaj_Mape_Swiata.MainWindow.time
czas gry w sekundach
Referenced by Poznaj_Mape_Swiata.MainWindow.Dobrze, Poznaj_Mape_Swiata.MainWindow.Timer_Tick.
DispatcherTimer Poznaj_Mape_Swiata.MainWindow.Timer
Zmienna systemowa odpowiedzialna za kontrole uplywu czasu
Referenced by Poznaj_Mape_Swiata.MainWindow.Czasomierz, Poznaj_Mape_Swiata.MainWindow.CzyWybranoStolice, Poznaj_Mape_Swiata.MainWindow.Dobrze, Poznaj_Mape_Swiata.MainWindow.Timer_Tick, Poznaj_Mape_Swiata.MainWindow.Zle.
int Poznaj_Mape_Swiata.MainWindow.ile_jeszcze
Zmienna odpowiedzialna za odliczanie stolic, ktore pozostaly do odgadniecia
Referenced by Poznaj_Mape_Swiata.MainWindow.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
int Poznaj_Mape_Swiata.MainWindow.zycie
zmienna liczaca zycia gracza
Referenced by Poznaj_Mape_Swiata.MainWindow.sprawdzMape, Poznaj_Mape_Swiata.MainWindow.Zle.
Image [] Poznaj_Mape_Swiata.MainWindow.zycia
Obiekt przechowujacy obrazki zycia na ekranie gracza
Referenced by Poznaj_Mape_Swiata.MainWindow.MainWindow, Poznaj_Mape_Swiata.MainWindow.Zle.
bool Poznaj_Mape_Swiata.MainWindow.hasBeenClicked
Zmienna kontrolujaca czyszczenie pola do wpisywania nazw krajow
Referenced by Poznaj_Mape_Swiata.MainWindow.Btnsprawdz_Click, Poznaj_Mape_Swiata.MainWindow.txt_woj_GotFocus.
bool Poznaj_Mape_Swiata.MainWindow.SecondStage
Gra dysponuje dwoma etapami - odgadnij kraj ze stolicy oraz pokaz na mapie (tu rozpoczecie drugiego etapu rozgrywki po poprawnym wpisaniu nazwy kraju)
Referenced by Poznaj_Mape_Swiata.MainWindow.CzyWybranoStolice, Poznaj_Mape_Swiata.MainWindow.LV_stolic_MouseLeave.
Dictionary<String, String> Poznaj_Mape_Swiata.MainWindow.dopasowanie
Obiekt przechowujacy pary zmiennych stolica-kraj
Referenced by Poznaj_Mape_Swiata.MainWindow.Btnsprawdz_Click, Poznaj_Mape_Swiata.MainWindow.Dopasuj.
Random Poznaj_Mape_Swiata.MainWindow.rnd
Obiekt odpowiedzialny za losowanie
Referenced by Poznaj_Mape_Swiata.MainWindow.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
RadioButton [] Poznaj_Mape_Swiata.MainWindow.radios
Tablica przechowujaca kontrolki typu radio z nazwami stolic
Referenced by Poznaj_Mape_Swiata.MainWindow.Btnsprawdz_Click, Poznaj_Mape_Swiata.MainWindow.CzyWybranoStolice, Poznaj_Mape_Swiata.MainWindow.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
String [] Poznaj_Mape_Swiata.MainWindow.nazwy_stolic
Tablica z nazwami stolic
Referenced by Poznaj_Mape_Swiata.MainWindow.Dopasuj, Poznaj_Mape_Swiata.MainWindow.PrzygotowaniePoziomu.
int Poznaj_Mape_Swiata.MainWindow.poziom
Zmienna przechowujaca dany poziom
Referenced by Poznaj_Mape_Swiata.MainWindow.CzyWybranoStolice, Poznaj_Mape_Swiata.MainWindow.Dobrze, Poznaj_Mape_Swiata.MainWindow.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.MainWindow.sprawdzMape, Poznaj_Mape_Swiata.MainWindow.UpdateLabels.
int Poznaj_Mape_Swiata.MainWindow.punkty
Zmienna przechowujaca liczbe punktow gracza
Referenced by Poznaj_Mape_Swiata.MainWindow.Btnsprawdz_Click, Poznaj_Mape_Swiata.MainWindow.sprawdzMape, Poznaj_Mape_Swiata.MainWindow.Timer_Tick, Poznaj_Mape_Swiata.MainWindow.UpdateLabels.
void Poznaj_Mape_Swiata.MainWindow.Dopasuj()
Metoda przechowująca pary: województwo-stolica
References Poznaj_Mape_Swiata.MainWindow.dopasowanie, Poznaj_Mape_Swiata.MainWindow.nazwy_stolic.
Referenced by Poznaj_Mape_Swiata.MainWindow.MainWindow.
void Poznaj_Mape_Swiata.MainWindow.UpdateLabels()
Metoda aktualizująca kontrolki przechowujących punkty i poziom
References Poznaj_Mape_Swiata.MainWindow.poziom, Poznaj_Mape_Swiata.MainWindow.punkty.
Referenced by Poznaj_Mape_Swiata.MainWindow.Btnsprawdz_Click, Poznaj_Mape_Swiata.MainWindow.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.PrzygotowaniePoziomu()
Metoda przygotowująca poziom do gry. Nastepuje w niej losowanie nazw stolic w czasie gry
References Poznaj_Mape_Swiata.MainWindow.ile_jeszcze, Poznaj_Mape_Swiata.MainWindow.nazwy_stolic, Poznaj_Mape_Swiata.MainWindow.poziom, Poznaj_Mape_Swiata.MainWindow.radios, Poznaj_Mape_Swiata.MainWindow.rnd, Poznaj_Mape_Swiata.MainWindow.UpdateLabels.
Referenced by Poznaj_Mape_Swiata.MainWindow.MainWindow, Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Czasomierz()
Metoda przechowująca dane licznika czasu na rundę
References Poznaj_Mape_Swiata.MainWindow.Timer, Poznaj_Mape_Swiata.MainWindow.Timer_Tick.
Referenced by Poznaj_Mape_Swiata.MainWindow.MainWindow.
Poznaj_Mape_Swiata.MainWindow.MainWindow()
Konstruktor programu inicjujacy gre
References Poznaj_Mape_Swiata.MainWindow.Czasomierz, Poznaj_Mape_Swiata.MainWindow.Dopasuj, Poznaj_Mape_Swiata.MainWindow.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.MainWindow.zycia.
Referenced by Poznaj_Mape_Swiata.MainWindow.Button_Again_Click.
void Poznaj_Mape_Swiata.MainWindow.Dobrze()
Metoda odpowiedzialna za reagowanie na poprawne odpowiedzi gracz
References Poznaj_Mape_Swiata.MainWindow.poziom, Poznaj_Mape_Swiata.MainWindow.time, Poznaj_Mape_Swiata.MainWindow.Timer.
Referenced by Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Zle()
Metoda odpowiedzialna za reagowanie na bledne odpowiedzi gracza oraz koniec gry.
References Poznaj_Mape_Swiata.MainWindow.Timer, Poznaj_Mape_Swiata.MainWindow.zycia, Poznaj_Mape_Swiata.MainWindow.zycie.
Referenced by Poznaj_Mape_Swiata.MainWindow.Btnsprawdz_Click, Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.WskazNaMapie()
Metoda odpowiedzialna za drugi etap rundy - wskazywanie na mapie
Referenced by Poznaj_Mape_Swiata.MainWindow.Btnsprawdz_Click.
int Poznaj_Mape_Swiata.MainWindow.CzyWybranoStolice()
Metoda sprawdzająca, która stolica została wybrana do odgadnięcia
Zwraca i-nr stolicy w przypadku poprawnego wyboru lub -1 w przypadku braku wyboru
References Poznaj_Mape_Swiata.MainWindow.poziom, Poznaj_Mape_Swiata.MainWindow.radios, Poznaj_Mape_Swiata.MainWindow.SecondStage, Poznaj_Mape_Swiata.MainWindow.Timer.
Referenced by Poznaj_Mape_Swiata.MainWindow.Btnsprawdz_Click, Poznaj_Mape_Swiata.MainWindow.LV_stolic_MouseLeave, Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Timer_Tick(object sender, EventArgs e)
Metoda odpowiedzialna za wyswietlanie oraz odliczanie czasu na gre w rundzie
sender Obiekt e Wydarzenie
References Poznaj_Mape_Swiata.MainWindow.punkty, Poznaj_Mape_Swiata.MainWindow.time, Poznaj_Mape_Swiata.MainWindow.Timer.
Referenced by Poznaj_Mape_Swiata.MainWindow.Czasomierz.
void Poznaj_Mape_Swiata.MainWindow.Btnsprawdz_Click(object sender, RoutedEventArgs e)
Metoda odpowiedzialna za sprawdzenie czy wybrana stolica pasuje do wpisanego wojewodztwa
sender Objekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.CzyWybranoStolice, Poznaj_Mape_Swiata.MainWindow.dopasowanie, Poznaj_Mape_Swiata.MainWindow.hasBeenClicked, Poznaj_Mape_Swiata.MainWindow.punkty, Poznaj_Mape_Swiata.MainWindow.radios, Poznaj_Mape_Swiata.MainWindow.UpdateLabels, Poznaj_Mape_Swiata.MainWindow.WskazNaMapie, Poznaj_Mape_Swiata.MainWindow.Zle.
void Poznaj_Mape_Swiata.MainWindow.txt_woj_GotFocus(object sender, RoutedEventArgs e)
Metoda odpowiedzialna za usuwanie domyslnego tekstu z pola do wpisywania nazwy województwa
sender Obiekt e Zdarzenie klikniecia w pole tekstowe
References Poznaj_Mape_Swiata.MainWindow.hasBeenClicked.
void Poznaj_Mape_Swiata.MainWindow.sprawdzMape(String nazwa, Button btn)
Metoda odpowiedzialna za sprawdzenie poprawnosci zaznaczenia wojewodztwa na mapie
nazwa Nazwa wojewodztwa btn Przycisk reprezentujacy obszar danego wojewodztwa
References Poznaj_Mape_Swiata.MainWindow.CzyWybranoStolice, Poznaj_Mape_Swiata.MainWindow.Dobrze, Poznaj_Mape_Swiata.MainWindow.ile_jeszcze, Poznaj_Mape_Swiata.MainWindow.poziom, Poznaj_Mape_Swiata.MainWindow.PrzygotowaniePoziomu, Poznaj_Mape_Swiata.MainWindow.punkty, Poznaj_Mape_Swiata.MainWindow.radios, Poznaj_Mape_Swiata.MainWindow.rnd, Poznaj_Mape_Swiata.MainWindow.UpdateLabels, Poznaj_Mape_Swiata.MainWindow.Zle, Poznaj_Mape_Swiata.MainWindow.zycie.
Referenced by Poznaj_Mape_Swiata.MainWindow.Button_Click_1, Poznaj_Mape_Swiata.MainWindow.Button_Click_10, Poznaj_Mape_Swiata.MainWindow.Button_Click_11, Poznaj_Mape_Swiata.MainWindow.Button_Click_12, Poznaj_Mape_Swiata.MainWindow.Button_Click_13, Poznaj_Mape_Swiata.MainWindow.Button_Click_14, Poznaj_Mape_Swiata.MainWindow.Button_Click_15, Poznaj_Mape_Swiata.MainWindow.Button_Click_16, Poznaj_Mape_Swiata.MainWindow.Button_Click_2, Poznaj_Mape_Swiata.MainWindow.Button_Click_3, Poznaj_Mape_Swiata.MainWindow.Button_Click_4, Poznaj_Mape_Swiata.MainWindow.Button_Click_5, Poznaj_Mape_Swiata.MainWindow.Button_Click_6, Poznaj_Mape_Swiata.MainWindow.Button_Click_7, Poznaj_Mape_Swiata.MainWindow.Button_Click_8, Poznaj_Mape_Swiata.MainWindow.Button_Click_9.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_1(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_2(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_3(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_4(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_5(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_6(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_7(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_8(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_9(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_10(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_11(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_12(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_13(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_14(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_15(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Click_16(object sender, RoutedEventArgs e)
Klikniecie w dany obszar wojewodztwa
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.sprawdzMape.
void Poznaj_Mape_Swiata.MainWindow.Button_Again_Click(object sender, RoutedEventArgs e)
Metoda, ktora po przegranej nastepuje mozliwosc ponownej gry
sender Obiekt e Zdarzenie klikniecia
References Poznaj_Mape_Swiata.MainWindow.MainWindow.
void Poznaj_Mape_Swiata.MainWindow.LV_stolic_MouseLeave(object sender, MouseEventArgs e)
Metoda odpowiedzialna za odczytanie z wylosowanej listy wybranego przez uzytkownika wojewodztwa
sender e
References Poznaj_Mape_Swiata.MainWindow.CzyWybranoStolice, Poznaj_Mape_Swiata.MainWindow.SecondStage.